coverage:
  precision: 2
  round: down
  range: "70...100"

parsers:
  cobertura:
    partials_as_hits: true  # Treat partial coverage as hits
    handle_missing_conditions: true  # Handle missing conditions

# Comment settings for PR notifications
comment:
  layout: "reach, diff, flags, files"
  behavior: default
  require_changes: false
  require_base: false
  require_head: true
  branches:
    - main
    - develop

# Ignore specific paths
ignore:
  - "**/bin/**"
  - "**/obj/**"
  - "**/TestResults/**"
  - "**/*.Designer.cs"
  - "**/*.AssemblyInfo.cs"