coverage:
  precision: 2
  round: down
  range: "70...100"

parsers:
  cobertura:
    partials_as_hits: true  # 將部分覆蓋計算為完全覆蓋
    handle_missing_conditions: true  # 處理缺失的條件

# 可選：設定通知和狀態檢查
comment:
  layout: "diff, flags, files"
  behavior: default
  require_changes: false

# 可選：忽略特定路徑
ignore:
  - "**/bin/**"
  - "**/obj/**"
  - "**/TestResults/**"
  - "**/*.Designer.cs"
  - "**/*.AssemblyInfo.cs"